name: lightgbm

model_path: res/models/
results: lightgbm_ranker

params:
  objective: lambdarank
  boosting_type: gbdt
  metric: ndcg
  ndcg_at:
    - 10
    - 30
    - 50
    - 100
  learning_rate: 0.05
  max_depth: -1
  num_leaves: 31
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42