name: lightgbm

params:
  objective: lambdarank
  boosting_type: gbdt
  metric: ndcg
  learning_rate: 0.01
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 10
num_boost_round: 300
verbose_eval: 10
seed: 42