categorical_features:
- ANIME_FEATURE IS_TV
- ANIME_FEATURE IS_ADULT
- ANIME_FEATURE COMEDY
- ANIME_FEATURE ACTION
- ANIME_FEATURE FANTASY
- ANIME_FEATURE ADVENTURE
- ANIME_FEATURE KIDS
- ANIME_FEATURE DRAMA
- ANIME_FEATURE SCI-FI
- ANIME_FEATURE MUSIC
- ANIME_FEATURE SHOUNEN
- ANIME_FEATURE SLICE OF LIFE
- USER_FEATURE REVIEW_COUNT
