hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

output:
  path: output
  submission: sample_submission.csv
  name: 2day-cross-validation-xgboost.csv
  
defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_path: res/models/
results: lightgbm_ranker