hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - _self_
  - data: dataset
  - tools: features
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_path: res/models/
results: lightgbm_ranker